---
Name: cms-niceties
---
#  @todo: UPGRADE: we applied some really basic CMS styling here,
# update as you see fit.


SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - resources/vendor/cms-niceties/client/css/cms/LeftAndMain.css


menu_groups:
  Content:
    priority: -10
    items:
      - SilverStripe-CMS-Controllers-CMSPagesController
      - SilverStripe-AssetAdmin-Controller-AssetAdmin
      - SilverStripe-SiteConfig-SiteConfigLeftAndMain
