---
Name: cms-niceties
---
#  @todo: UPGRADE: we applied some really basic CMS styling here,
# update as you see fit.


SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'sunnysideup/cms-niceties: client/dist/css/cms/LeftAndMain.css'

SilverStripe\Dev\TaskRunner:
  css: 'nothinghere'

---
Name: cms-niceties-hack
Only:
    classexists:
        - SilverStripe\Admin\LeftAndMain
---


SilverStripe\Dev\TaskRunner:
  css:
    0: 'sunnysideup/cms-niceties: client/dist/css/cms/task-runner.css'
