---
Name: cms-niceties
---
#  @todo: UPGRADE: we applied some really basic CMS styling here,
# update as you see fit.


SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - resources/vendor/sunnysideup/cms-niceties/client/dist/css/cms/LeftAndMain.css
